services:
  github-runner:
    build:
      context: ops/docker/github-runner
      dockerfile: Dockerfile
  helm-deploy:
    build:
      context: ops/docker/helm-deploy
      dockerfile: Dockerfile
  playwright-runner:
    build:
      context: ops/docker/playwright-runner
      dockerfile: Dockerfile
    volumes:
      - ./tests/playwright-runner:/app
  rust-ci-runner:
    build:
      context: ops/docker/rust-ci-runner
      dockerfile: Dockerfile
  rust-releaser:
    image: aaaaaa/rust-releaser:latest
    container_name: rust-releaser
    build:
      context: ops/docker/rust-releaser
      dockerfile: Dockerfile