name: "[Action] Semantic Release"
description: "Use semantic-release to automate versioning and releases"

inputs:
  release-type:
    description: "The type of release"
    required: false
  token:
    description: "Token to use for pushing tags/releases (e.g., GitHub App token)"
    required: false
  package-path:
    description: "Path to the package directory (repo-relative), e.g. ops/docker/helm-deploy"
    required: true
  package-name:
    description: "Package name used for tag prefix, e.g. helm-deploy"
    required: true

outputs:
  version:
    description: "The new version number (from exec plugin writing to $GITHUB_OUTPUT)"
    value: ${{ steps.semantic-release.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # semantic-release requires all commits/tags
        token: ${{ inputs.token || github.token }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install dependencies
      shell: bash
      run: npm ci || true

    - name: Build
      shell: bash
      run: npm run build || true

    - name: Set semantic-release config file
      id: set-config
      shell: bash
      run: |
        set -euo pipefail

        if [[ -n "${{ inputs.release-type }}" ]]; then
          if [[ -f ".releaserc.${{ inputs.release-type }}.js" ]]; then
            echo "release_config=--extends=./.releaserc.${{ inputs.release-type }}.js" >> "$GITHUB_OUTPUT"
          elif [[ -f ".releaserc.${{ inputs.release-type }}.json" ]]; then
            echo "release_config=--extends=./.releaserc.${{ inputs.release-type }}.json" >> "$GITHUB_OUTPUT"
          fi
        else
          # semantic-release v24 supports --extends (not --config)
          if [[ -f ".releaserc.js" ]]; then
            echo "release_config=--extends=./.releaserc.js" >> "$GITHUB_OUTPUT"
          elif [[ -f ".releaserc.json" ]]; then
            echo "release_config=--extends=./.releaserc.json" >> "$GITHUB_OUTPUT"
          fi
        fi

    - name: Run semantic-release
      shell: bash
      id: semantic-release
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        set -euo pipefail

        pkg_dir="${GITHUB_WORKSPACE}/${{ inputs.package-path }}"
        pkg_name="${{ inputs.package-name }}"
        pkg_json="$pkg_dir/package.json"
        created_pkg_json="false"

        if [[ ! -d "$pkg_dir" ]]; then
          echo "package-path does not exist: $pkg_dir" >&2
          exit 1
        fi

        if [[ ! -f "$pkg_json" ]]; then
          printf '{\n  "name": "%s",\n  "version": "0.0.0",\n  "private": true\n}\n' "$pkg_name" > "$pkg_json"
          created_pkg_json="true"
        fi

        cleanup() {
          if [[ "$created_pkg_json" == "true" ]]; then
            rm -f "$pkg_json" || true
          fi
        }
        trap cleanup EXIT

        cd "$pkg_dir"

        npm install --no-save --no-audit --no-fund \
          semantic-release \
          semantic-release-monorepo \
          @semantic-release/commit-analyzer \
          @semantic-release/exec \
          @semantic-release/github \
          @semantic-release/release-notes-generator \
          conventional-changelog-conventionalcommits

        npx semantic-release ${{ steps.set-config.outputs.release_config }}
